# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161105_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='foto'),
        ),
    ]
