# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161106_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='foto'),
        ),
    ]
